<?php

use App\Models\Color;
use Illuminate\Database\Seeder;

class ColorsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $colors = [
            "Alice Blue" => "aliceblue",
            "Antique White" => "antiquewhite",
            "Aqua" => "aqua",
            "Aquamarine" => "aquamarine",
            "Azure" => "azure",
            "Beige" => "beige",
            "Bisque" => "bisque",
            "Black" => "black",
            "Blanched Almond" => "blanchedalmond",
            "Blue" => "blue",
            "Blue Violet" => "blueviolet",
            "Brown" => "brown",
            "Burly Wood" => "burlywood",
            "Cadet Blue" => "cadetblue",
            "Chartreuse" => "chartreuse",
            "Chocolate" => "chocolate",
            "Coral" => "coral",
            "Cornflower Blue" => "cornflowerblue",
            "Cornsilk" => "cornsilk",
            "Crimson" => "crimson",
            "Cyan" => "cyan",
            "Dark Blue" => "darkblue",
            "Dark Cyan" => "darkcyan",
            "Dark Golden Rod" => "darkgoldenrod",
            "Dark Gray" => "darkgray",
            "Dark Grey" => "darkgrey",
            "Dark Green" => "darkgreen",
            "Dark Khaki" => "darkkhaki",
            "Dark Magenta" => "darkmagenta",
            "Dark Olive Green" => "darkolivegreen",
            "Dark Orange" => "darkorange",
            "Dark Orchid" => "darkorchid",
            "Dark Red" => "darkred",
            "Dark Salmon" => "darksalmon",
            "Dark Sea Green" => "darkseagreen",
            "Dark Slate Blue" => "darkslateblue",
            "Dark Slate Gray" => "darkslategray",
            "Dark Slate Grey" => "darkslategrey",
            "Dark Turquoise" => "darkturquoise",
            "Dark Violet" => "darkviolet",
            "Deep Pink" => "deeppink",
            "Deep Sky Blue" => "deepskyblue",
            "Dim Gray" => "dimgray",
            "Dodger Blue" => "dodgerblue",
            "Fire Brick" => "firebrick",
            "Floral White" => "floralwhite",
            "Forest Green" => "forestgreen",
            "Fuchsia" => "fuchsia",
            "Gainsboro" => "gainsboro",
            "Ghost White" => "ghostwhite",
            "Gold" => "gold",
            "Golden Rod" => "goldenrod",
            "Gray" => "gray",
            "Grey" => "grey",
            "Green" => "green",
            "Green Yellow" => "greenyellow",
            "Honey Dew" => "honeydew",
            "Hot Pink" => "hotpink",
            "Indian Red" => "indianred",
            "Indigo" => "indigo",
            "Ivory" => "ivory",
            "Khaki" => "khaki",
            "Lavender" => "lavender",
            "Lavender Blush" => "lavenderblush",
            "Lawn Green" => "lawngreen",
            "Lemon Chiffon" => "lemonchiffon",
            "Light Blue" => "lightblue",
            "Light Coral" => "lightcoral",
            "Light Cyan" => "lightcyan",
            "Light Golden Rod Yellow" => "lightgoldenrodyellow",
            "Light Gray" => "lightgray",
            "Light Grey" => "lightgrey",
            "Light Green" => "lightgreen",
            "Light Pink" => "lightpink",
            "Light Salmon" => "lightsalmon",
            "Light Sea Green" => "lightseagreen",
            "Light Sky Blue" => "lightskyblue",
            "Light Slate Gray" => "lightslategray",
            "Light Slate Grey" => "lightslategrey",
            "Light Steel Blue" => "lightsteelblue",
            "Light Yellow" => "lightyellow",
            "Lime" => "lime",
            "Lime Green" => "limegreen",
            "Linen" => "linen",
            "Magenta" => "magenta",
            "Maroon" => "maroon",
            "Medium Aqua Marine" => "mediumaquamarine",
            "Medium Blue" => "mediumblue",
            "Medium Orchid" => "mediumorchid",
            "Medium Purple" => "mediumpurple",
            "Medium Sea Green" => "mediumseagreen",
            "Medium Slate Blue" => "mediumslateblue",
            "Medium Spring Green" => "mediumspringgreen",
            "Medium Turquoise" => "mediumturquoise",
            "Medium Violet Red" => "mediumvioletred",
            "Midnight Blue" => "midnightblue",
            "Mint Cream" => "mintcream",
            "Misty Rose" => "mistyrose",
            "Moccasin" => "moccasin",
            "Navajo White" => "navajowhite",
            "Navy" => "navy",
            "Old Lace" => "oldlace",
            "Olive" => "olive",
            "Olive Drab" => "olivedrab",
            "Orange" => "orange",
            "Orange Red" => "orangered",
            "Orchid" => "orchid",
            "Pale Golden Rod" => "palegoldenrod",
            "Pale Green" => "palegreen",
            "Pale Turquoise" => "paleturquoise",
            "Pale VioletRed" => "palevioletred",
            "Papaya Whip" => "papayawhip",
            "Peach Puff" => "peachpuff",
            "Peru" => "peru",
            "Pink" => "pink",
            "Plum" => "plum",
            "Powder Blue" => "powderblue",
            "Purple" => "purple",
            "Rebecca Purple" => "rebeccapurple",
            "Red" => "red",
            "Rosy Brown" => "rosybrown",
            "Royal Blue" => "royalblue",
            "Saddle Brown" => "saddlebrown",
            "Salmon" => "salmon",
            "Sandy Brown" => "sandybrown",
            "Sea Green" => "seagreen",
            "Sea Shell" => "seashell",
            "Sienna" => "sienna",
            "Silver" => "silver",
            "Sky Blue" => "skyblue",
            "Slate Blue" => "slateblue",
            "Slate Gray" => "slategray",
            "Slate Grey" => "slategrey",
            "Snow" => "snow",
            "Spring Green" => "springgreen",
            "Steel Blue" => "steelblue",
            "Tan" => "tan",
            "Teal" => "teal",
            "Thistle" => "thistle",
            "Tomato" => "tomato",
            "Turquoise" => "turquoise",
            "Violet" => "violet",
            "Wheat" => "wheat",
            "White" => "white",
            "White Smoke" => "whitesmoke",
            "Yellow" => "yellow",
            "Yellow Green" => "yellowgreen",
        ];
        foreach ($colors as $color => $value) {
            Color::updateOrCreate(['name' => $color], ['name' => $color, 'value' => $value]);
        }
    }
}
